import { Stack, Text, DetailsList, SelectionMode, PrimaryButton } from '@fluentui/react'
import type { IColumn } from '@fluentui/react'
import ReportBuilder from '../components/ReportBuilder'

const Reports = () => {
  const reports = [
    { name: 'Email Activity Q3', service: 'Exchange Online', dateRange: '01/07/2024 - 30/09/2024', status: 'Completed', generatedBy: 'admin@contoso.com' },
    { name: 'Teams Usage Weekly', service: 'Microsoft Teams', dateRange: '28/09/2024 - 04/10/2024', status: 'Completed', generatedBy: 'admin@contoso.com' },
    { name: 'SharePoint Site Usage', service: 'SharePoint Online', dateRange: '01/09/2024 - 30/09/2024', status: 'Processing', generatedBy: 'policy.admin@contoso.com' },
  ]

  const columns: IColumn[] = [
    { key: 'name', name: 'Report Name', fieldName: 'name', minWidth: 150 },
    { key: 'service', name: 'Service', fieldName: 'service', minWidth: 120 },
    { key: 'dateRange', name: 'Date Range', fieldName: 'dateRange', minWidth: 150 },
    { key: 'status', name: 'Status', fieldName: 'status', minWidth: 100 },
    { key: 'generatedBy', name: 'Generated By', fieldName: 'generatedBy', minWidth: 150 },
    { key: 'actions', name: 'Actions', fieldName: 'actions', minWidth: 100 },
  ]

  return (
    <Stack tokens={{ childrenGap: 24 }}>
      <Stack horizontal horizontalAlign="space-between">
        <div>
          <Text variant="xxLarge" styles={{ root: { fontWeight: 600 } }}>Usage Reports</Text>
          <Text variant="large" styles={{ root: { color: '#605e5c' } }}>Analyze usage patterns across Microsoft 365 services.</Text>
        </div>
        <PrimaryButton text="Create Report" />
      </Stack>

      <Stack tokens={{ childrenGap: 16 }}>
        <Text variant="xLarge" styles={{ root: { fontWeight: 600 } }}>Report Builder</Text>
        <ReportBuilder />
      </Stack>

      <Stack tokens={{ childrenGap: 16 }}>
        <Text variant="xLarge" styles={{ root: { fontWeight: 600 } }}>Generated Reports</Text>
        <DetailsList
          items={reports}
          columns={columns}
          selectionMode={SelectionMode.none}
        />
      </Stack>
    </Stack>
  )
}

export default Reports